version: "3"
services:
  zookeeper:
    image: "examples/zookeeper"
    build: "./zookeeper"
    #environment:
      #LOG_LEVEL: "INFO"
      #MY_ID: 1
    ports:
    - 2181:2181

  kafka:
    image: "examples/kafka"
    build: "./kafka"
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      #LOG_LEVEL: "INFO"
    ports:
    - 9092:9092
    depends_on:
    - "zookeeper"

#  kafka-manager:
#    image: "examples/kafka-manager"
#    build: "./kafka-manager"
#    environment:
#      ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_CLUSTER: "kafka"
#      KAFKA_VERSION: "0.11.0.0"
#    ports:
#    - 8083:9000
#    depends_on:
#    - "kafka"

#  kafka-rest-proxy:
#    image: "examples/kafka-rest-proxy"
#    build: "./kafka-rest-proxy"
#    environment:
#      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
#      ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
#    ports:
#    - 8082:8082
#    depends_on:
#    - "kafka"
#    - "schema-registry"

  schema-registry:
    image: "examples/schema-registry"
    build: "./schema-registry"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
    - 8081:8081
    depends_on:
    - "kafka"

  producer:
    image: "examples/producer"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
    - "kafka"
    - "schema-registry"

  producer:
    image: "examples/consumer"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
    - "kafka"
    - "schema-registry"
