version: "3"

services:
  kafka:
    environment:
      LOCAL: "yes"
    #  LISTENERS: "PLAINTEXT://127.0.0.1:9092"

  producer:
    image: "alpine:3.7"
    entrypoint: |
      tail -f /dev/null
    depends_on:
    - "kafka"
    - "schema-registry"

  consumer:
    image: "alpine:3.7"
    entrypoint: |
      tail -f /dev/null
    depends_on:
    - "kafka"
    - "schema-registry"