version: "3"
services:
  zookeeper:
    image: "akka-kafka/zookeeper"
    build: "./zookeeper"
    #environment:
      #LOG_LEVEL: "INFO"
      #MY_ID: 1
    ports:
    - 2181:2181

  kafka:
    image: "akka-kafka/kafka"
    build: "./kafka"
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      #LOG_LEVEL: "INFO"
    ports:
    - 9092:9092
    depends_on:
    - "zookeeper"

  kafka-manager:
    image: "akka-kafka/kafka-manager"
    build: "./kafka-manager"
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CLUSTER: "kafka"
      KAFKA_VERSION: "0.11.0.0"
    ports:
    - 8081:9000
    depends_on:
    - "kafka"

  examples:
    image: "akka-kafka/examples"
    build: "./examples"
    ports:
    - 8080:9000
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
    - "kafka"